//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DeptID { get; set; }
        public byte[] IMageData { get; set; }
        public string FileName { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ReportingTo { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Address2 { get; set; }
    
        public virtual User User { get; set; }
        public virtual Department Department { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Employee Employees1 { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
